import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { SearchBar } from "~/components/searchBar";
import { HomeNavigation } from "~/components/homeNavigation";

const Home: NextPage = () => {

  

  return (
    <>
      <Head>
        <title>Interview Questions Library</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
        Interview Questions Library
      </h1>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
        <Link
          className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
          href="https://create.t3.gg/en/usage/first-steps"
          target="_blank"
        >
          <h3 className="text-2xl font-bold">First Steps →</h3>
          <div className="text-lg">
            Just the basics - Everything you need to know about this website
          </div>
        </Link>
        <Link
          className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
          href="https://create.t3.gg/en/introduction"
          target="_blank"
        >
          <h3 className="text-2xl font-bold">Documentation →</h3>
          <div className="text-lg">
            Learn more about Create T3 App and libraries I used to create this application
          </div>
        </Link>
      </div>
      <div className="w-full flex flex-col items-center gap-2">
        <AuthShowcase />
      </div>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  return (
    <div className="w-full flex flex-col items-center justify-center gap-4 text-white">
      
      
      {(() => {
        if(sessionData == null) {
          
          return (
            <>
            <p>In order to use this app, you need to have an account.</p>
              <button
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={() => void signIn()}
              >
                {"Sign in"}
              </button>
            </>
            
          ) 
        }else{
          return (
            <>
              <SearchBar />
            </>
            
          )
        }
      })()}

      {(() => {

        if (sessionData?.user.role == "admin") {
          return (
            <>
              <Link className="btn btn-primary text-white" href="/role">
                Manage User Role
              </Link>
            </>
            
          )
        }
      })()}
      
    </div>
  );
  

  
};
